use default app namespace for translations
EyeSeeTea/dhis2-app-skeleton pull request #92
Opened 2024-06-26 11:06 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8694ubx3x

### :memo: Implementation
- [x] Set default namespace in `app-context.ts`

### :video_camera: Screenshots/Screen capture
<img width="654" alt="Screenshot 2024-06-26 at 12 05 36" src="https://github.com/EyeSeeTea/dhis2-app-skeleton/assets/37223065/bfd49e50-b314-4dc4-a92e-ab8ce4dc26f0">

### :fire: Notes to the tester
I added a translation for `Section` to test

#8694ubx3x

2024-07-01 08:35 UTC, MiquelAdell approved these changes
Sección is ok :-)

2024-07-04 03:34 UTC, eperedo requested changes

2024-07-04 03:34 UTC, eperedo commented on src/webapp/contexts/app-context.ts
> +    i18n.setDefaultNamespace("dhis2-skeleton-app");
Forcing the namespace was a fix for existing applications, but for new applications we decided to add the namespace in the `t` method so we can remove this.

You can see more details in this [PR](https://github.com/EyeSeeTea/dhis2-app-skeleton/pull/90).

2024-07-23 18:38 UTC, adrianq commented
Superseded by https://github.com/EyeSeeTea/dhis2-app-skeleton/pull/90

2024-07-23 18:38 UTC, closed without merging